CONTIKI = ../..


all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors \
	 week3_a week3_a_broadcast \
	 week4-udp-server week4-udp-client\
	 week4-h-sender week4-h-rcver week4-h-forward

include $(CONTIKI)/Makefile.include
